spring:
  application:
    name: gami-ai
  datasource:
    url: jdbc:postgresql://tramway.proxy.rlwy.net:21803/railway
    username: postgres
    password: gMftyHRQixCGqJyCLdaTNZrQfeHDBZeT
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: pZGV5hKRLU4z8m2oBVY3Dzm2f0YSXb7qG6Wd8PfJzFMPTyxC4bT0fCxytgQWER9SeVMRyEVOnVkbSD0rtdEiPw==
  expirationMs: 86400000

jasypt:
  encryptor:
    password: gami_ai_secret
    algorithm: PBEWithMD5AndDES

execution:
  server:
    url: http://localhost:8001

ai:
  agent:
    url: http://localhost:4000

engagement:
  max-actions: 5

cors:
  allowed-origins: http://localhost:3000