spring:
  application:
    name: gami-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/gami_ai
    username:  gami_ai_user
    password:  gami_ai_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your_jwt_secret
  expirationMs: 86400000

jasypt:
  encryptor:
    password: gami_ai_secret
    algorithm: gami_ai_algorithm

execution:
  server:
    url: https://gami-ai-exec-production.up.railway.app

ai:
  agent:
    url: http://gami-ai-agent-production.up.railway.app

engagement:
  max-actions: 5

cors:
  allowed-origins: http://localhost:3000